# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'WeatherApp' do
    pod 'RxSwift', '6.6.0'
    pod 'RxCocoa', '6.6.0'
    pod 'RxCoreLocation', '~> 1.5.1'
end
